CREATE TABLE IF NOT EXISTS users (
 id UUID PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(100), google_subject VARCHAR(255) UNIQUE,
 CHECK (password_hash IS NOT NULL OR google_subject IS NOT NULL),
 role VARCHAR(10) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER','ADMIN')),
 status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','LOCKED')),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_login_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS user_profiles (
 user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 nickname VARCHAR(40) NOT NULL, nickname_key VARCHAR(40) NOT NULL UNIQUE,
 full_name VARCHAR(120), avatar_url VARCHAR(1000), city VARCHAR(120), bio VARCHAR(1000)
);
CREATE TABLE IF NOT EXISTS user_settings (
 user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 location_enabled BOOLEAN NOT NULL DEFAULT FALSE,
 notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
 recommendations_enabled BOOLEAN NOT NULL DEFAULT TRUE,
 onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
 interest_codes VARCHAR(1000) NOT NULL DEFAULT '[]'
);
CREATE TABLE IF NOT EXISTS refresh_sessions (
 id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 refresh_hash VARCHAR(64) NOT NULL UNIQUE,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 revoked BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON refresh_sessions(user_id);
CREATE INDEX IF NOT EXISTS ix_sessions_expiry ON refresh_sessions(expires_at);
